print("**Following are the list of functions avaialable in python(3.6.4)")
print("**Type dir(__builtins__) to see them")
dir(__builtins__)
print("\n**To know about a fcn, type help(function name)")
print("**eg:help(print)")
help(print)
print("**To know about the list of modules")
print("**Type help(""modules"") to see them")
help("modules")
print("To import a module type, import.module name")
print("eg:import math")
import math
math.pow(3,5)
print("\n**To know about a module, type help(module name)")
print("eg:help(math)")
help(math)
