from tkinter import *
myG1=Tk()
myG2=Tk()
myG1.title("SProg")
myG2.title("CProg")
#20 and 70 are spawn points
myG1.geometry("500x500+100+50")
myG2.geometry("500x500+700+50")
a=StringVar()
#mainloop function is like getch()
def c1():
    b=a.get()
    lab1=Label(myG2,text=b).pack()
def c2():
    lab2=Label(text="You used c2").pack()
myLb=Label(text="Hello all!!",fg='green',bg='black')
myLb.pack()
myLb2=Label(text="2nd label!",fg='red',bg='yellow').pack()
myLb3=Label(myG2,text="3rd label",fg="RED",bg="BLUE")
myLb3.place(x=300,y=450)
myLb4=Label(text="Placing!",fg='violet',bg='magenta').place(x=200,y=100)
#myLb5=Label(text="R=0,C=0!",fg='red',bg='blue').grid(row=0,column=0)
#myLb6=Label(text="R=1,C=0!",fg='violet',bg='magenta').grid(row=1,column=0,sticky="w")
myBut1=Button(text="Click",fg="Black",bg="Yellow",command=c1).place(x=20,y=40)
myBut2=Button(text="Enter",fg="Blue",bg="Yellow",font=30,command=c2).place(x=20,y=70)
Tx1=Entry().pack()
Tx2=Entry(textvariable=a).pack()
myG1.mainloop()
myG2.mainloop()
