arr1=["hello","how","you","doin"]
arr2=[23,16,89,57,32]
list3=[528,45.973,"haha"]
tuple1=("yo","yolo",34)
print(arr1)
print(arr2)
print(list3)
input("Enter to continue:")
print(arr1[1])
input("Enter to continue:")
print(arr1[1:4])
input("Enter to continue:")
print(len(arr1))
input("Enter to continue:")
print(arr1[-3:-1])
input("Enter to continue:")
print(arr1[-1])
input("Enter to continue:")
arr1.append("?")
print(arr1)
input("Enter to continue:")
print(arr1.index("?"))
input("Enter to continue:")
arr1.reverse()
arr1.remove("?")
print(arr1)
input("Enter to continue:")
arr1.pop()
print(arr1)
print(dir())
print(tuple1)
print("Array and List are the same")
print("Tuple is similar to List but data cannot be deleted from it once created")


