a="xylophone"
b=47
print(a+str(b))
input("Enter to proceed")
print(len(a)+b)
input("Enter to proceed")
print(a.upper())
input("Enter to proceed")
print(a[0])
input("Enter to proceed")
print(a[:3])
input("Enter to proceed")
print(a[4:9])
input("Enter to proceed")
print(a[2:4]*5)
input("Enter to proceed")
print(a[2:-4])
print(a[2:5])
input("Enter to EXIT")
